- name: apt-get update
  apt: update_cache=yes
  sudo: yes

- name: Install base packages
  apt: pkg={{item}}
  sudo: yes
  with_items:
      - bzr
      - git-core
      - gnupg
      - make
      - zsh
      # Needed by ci.linaro.org
      - dput
